#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'boto',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/boto',
   :ref => 'master'

cookbook 'system',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/system',
   :ref => 'master'

cookbook 'rightscale',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/rightscale',
   :ref => 'master'

cookbook 'rest_connection',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/rest_connection',
   :ref => 'master'
  
cookbook 'resolver',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/resolver',
   :ref => 'master'

cookbook 'apache2',
  :git => 'https://github.com/opscode-cookbooks/apache2',
  :ref => 'master'
      
cookbook 'cron',
  :git => 'https://github.com/opscode-cookbooks/cron',
  :ref => 'master'

cookbook 'ntp',
  :git => 'https://github.com/opscode-cookbooks/ntp',
  :ref => 'master'
   
cookbook 'sudo',
  :git => 'https://github.com/opscode-cookbooks/sudo',
  :ref => 'master'

cookbook 'postfix',
  :git => 'https://github.com/opscode-cookbooks/postfix',
  :ref => 'master'

cookbook 'python',
  :git => 'https://github.com/opscode-cookbooks/python',
  :ref => 'master'

# currently using un-pushed flaccid fork
cookbook 'collectd',
  :git => 'https://github.com/flaccid/chef-collectd',
  :ref => 'master'
#cookbook 'collectd',
#  :git => 'https://github.com/coderanger/chef-collectd',
#  :ref => 'master'

cookbook 'collectd_plugins',
  :git => 'https://github.com/coderanger/chef-collectd_plugins',
  :ref => 'master'